### ISSUE TITLE
How to setup Perplex?

### ISSUE THREAD

**Issue by stewieboo** [EthanC/Perplex#10]
I don't know much about Python but would love to use this script. Could you please provide a step-by-step tutorial? Thanks.

**Comment by Khroners** [comment]
Install Python3 (from website for windows store)
Install dependancies (in a terminal, like powershell) : 
pip3 install loguru plexAPI httpx pypresence pylint black
Edit config_example.json and enter your Plex logins and your API key from TMDB. Save it and rename it "config.json".
Run PowerShell, and cd into the directory where you extracted the repo and run : 
python .\perplex.py
