### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rollecode** [EthanC/Perplex#11]
Getting the following when running `python3 perplex.py`:

```
  File "perplex.py", line 91
    if (level := settings["severity"].upper()) != "DEBUG":
              ^
SyntaxError: invalid syntax
```

All deps are ok, config.json looks fine. How to resolve?

**Comment by rollecode** [comment]
Seems to be working fine when I comment out that if block.

**Comment by EthanC** [comment]
You are using a version of Python prior to 3.8. As noted in the README, Python versions prior to 3.10 are not supported.

**Comment by rollecode** [comment]
Oh I thought it was 3.8 but it was 3.7. Thanks.
