### ISSUE TITLE
Fetched active media session of unknown type: <class 'plexapi.video.EpisodeSession'>

### ISSUE THREAD

**Issue by nagmus** [EthanC/Perplex#18]
I'm getting errors when playing media.

Fetched active media session of unknown type: <class 'plexapi.video.EpisodeSession'>

I'm also wondering if I need to set something up in Discord?

**Comment by trothenberg** [comment]
plexapi was changed a few months back.  I would install plexapi version 4.8.0 for now until this project gets updated.

`pip install plexapi==4.8.0`

**Comment by nagmus** [comment]
That did the trick, cheers!
