### ISSUE TITLE
Fetch session info from specific user

### ISSUE THREAD

**Issue by alecaputo13** [EthanC/Perplex#2]
I have another enanchment feature to request. I have my own Plex server where i invited many friends. If any of them is watching something on my server the script detects the watching status as if I was watching it. 
It would be cool if we could choose for which user fetching session to.

**Comment by EthanC** [comment]
This is a limitation that I'm aware of, but I have yet to find a comfortable solution for it. The [`Movie`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/video.py#L264) and [`Episode`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/video.py#L712) classes in [pkkid/python-plexapi](https://github.com/pkkid/python-plexapi) do not appear to have any ability to discern which user (name or id) is responsible for the session.

For anybody looking to contribute this Issue, there are two theoretical solutions - the first of which would be preferred:
1. Add an array to [`config.json`](https://github.com/EthanC/Perplex/blob/abdddb30c0ff4315f020fef46a55b3b104f63279/config_example.json), similar to the [`servers` array](https://github.com/EthanC/Perplex/blob/abdddb30c0ff4315f020fef46a55b3b104f63279/config_example.json#L9), and prioritize sessions from users in this list.
2. First, [prompt](https://github.com/EthanC/Perplex/blob/abdddb30c0ff4315f020fef46a55b3b104f63279/perplex.py#L114) the user to choose one of the [active sessions](https://github.com/EthanC/Perplex/blob/abdddb30c0ff4315f020fef46a55b3b104f63279/perplex.py#L198) if there are multiple. Then save a unique identifier of the user responsible for the session and use it for subsequent updates.

**Comment by alecaputo13** [comment]
I don't know if this can help but there's an old script like this which had an option called 'listen for user' https://github.com/Phineas05/discord-rich-presence-plex

**Comment by EthanC** [comment]
Nice! It seems that [pkkid/python-plexapi](https://github.com/pkkid/python-plexapi) doesn't explicitly expose the `usernames` array anywhere, but it does exist.

I've added a `users` field to the config, just enter Plex usernames in there and Perplex will use the first one that it finds active.
