### ISSUE TITLE
Enable support for multiple servers at the same time

### ISSUE THREAD

**Issue by alecaputo13** [EthanC/Perplex#5]
Hi, in the config file you can set multiple server but, for what's i've seen, if the first server is found the others are ignored and the script won't try to fetch sessions from the others.

Since i own multiple server it would be cool if the script continuously looks for session from all the servers set in the config.json.

**Comment by EthanC** [comment]
What you're describing sounds like the intended behavior?

The servers listed in the configuration file should be in the order of priority, place the server that you expect to fetch your presence from at the beginning of the list. If a server is not found, it will move on to the next.

In the current command-line implementation of the app, there is no feasible way to _choose_ which server you'd like to fetch a presence from. This would require user input each time the app tries to fetch your presence.

**Comment by alecaputo13** [comment]
Didn't know that was the intended behaviour. Maybe I can achieve what i want running two instances of the script, prioritizing different server on each instance.

Thanks for the help anyway :)

EDIT: I can confirm that multiple istance of the script with different server priorities work
