### ISSUE TITLE
Use Token instead of Username Password

### ISSUE THREAD

**Issue by KaiDevrim** [EthanC/Perplex#9]
Hi! Using the PlexAPI you can instead of asking for the username and password and 2FA token directly, you can instead use a plex token like so:
```
from plexapi.server import PlexServer
baseurl = 'http://plexserver:32400'
token = '2ffLuB84dqLswk9skLos'
plex = PlexServer(baseurl, token)
```

The PlexAPI docs have more info.

**Comment by EthanC** [comment]
It's not officially supported, but Perplex is already capable of this. Place your authentication token in `auth.txt`, and it should use that to authorize rather than a username and password.
